-   id: terraform-datadog-docs
    name: Generated Terraform DataDog Docs
    description: Makes a doc table per -variables.tf file
    entry: tf_datadog_docs
    language: python
    language_version: python3